### ISSUE TITLE
[Feature request] Split edges -- add support for separate actions when hitting a section of an edge

### ISSUE THREAD

**Issue by w-jablonski** [AndreasBackx/waycorner#12]
Add support for separate actions when hitting a certain section of an edge. Probably best defined using a percentage/fraction of the edge. E.g from 0% to 25% etc. This would be very powerful as you could e.g go to any of your workspaces intuitively just using a single edge.

Is anyone interested/planning such an extension of edges functionality, maybe @jhpaques ? Sadly I am only beginning with coding.

**Comment by jhpaques** [comment]
I will look into it. Shouldn't be too difficult.

**Comment by w-jablonski** [comment]
Thanks for the interest. 
However, being honest I must say I've lost interest in waycorner, at least for now. Simple swaybar + i3status-rs serves me well for time being! As such, I shall close this issue now, pending anyone else showing interest...
Again, thank you!
