### ISSUE TITLE
Expand across screen width or place in center 

### ISSUE THREAD

**Issue by kmafeni04** [AndreasBackx/waycorner#17]
I want to use waycorner as a way to show and hide waybar, sort of how a dock works, wanted to know if it was possible to have the activation area for across the width of my screen or have an option to place the hot corner in the center rather than in the corners

**Comment by AndreasBackx** [comment]
You could have it around all edges of the screen. Though you cannot have it in the center. Perhaps if you explain in more detail what you're trying to do, I can provide better help.

**Comment by AndreasBackx** [comment]
Closing due to lack of response.
