### ISSUE TITLE
Please update readme file 

### ISSUE THREAD

**Issue by mahaveergurjar** [AndreasBackx/waycorner#18]
How to add keyboard shortcut key and script file in the hot corner conf file please tell me

**Comment by AndreasBackx** [comment]
There is no configuration for a shortcut key, you have to set this up yourself in your desktop environment. So if you're using sway, Hyprland, or similar, they can link a shortcut to a keybinding. See bindsym here: https://man.archlinux.org/man/sway.5. Keybinding functionality is as of right now out of the scope of this project.

**Comment by Purian23** [comment]
Is this still a true statement in 2025 @AndreasBackx ? I am trying to get a shortcut in place that starts an overview mode as in Gnome. I have the Hyprland plugin installed called Expo, it works via shortcut key. However, I cannot figure out a way to bind that to Waycorner.

**Comment by AndreasBackx** [comment]
Waycorner is a way to trigger a command via locations, likely corners, on your screen. I do not see how shortcuts come into play here.

@Purian23 what you are asking is to be able to trigger expo via waycorner? You'll have to find out how to trigger it via the commandline and then you input that in the waycorner config. This will likely be via `hyprctl` but I cannot help you further unfortunately.
