### ISSUE TITLE
No hot-corner on hyprland and message from client-toolkit: interface 'wl_surface' has no event 2

### ISSUE THREAD

**Issue by siretty** [AndreasBackx/waycorner#20]
When used on Hyprland, the executable (specifically the `smithay-client-toolkit` crate) prints a message: `interface 'wl_surface' has no event 2`. The hot-corner functionality does not work in these cases.

This is a known issue, fixed in version `0.16.1` of the [smithay-client-toolkit](https://github.com/Smithay/client-toolkit).

The issue in the client-toolkit can be found [here](https://github.com/Smithay/client-toolkit/pull/406).

**Comment by siretty** [comment]
Resolved by PR #21.

**Comment by lacamar** [comment]
I just encountered this issue and I was able to deal with it by installing it via cargo without the `--locked` flag, opposed to the directions in the readme. I'm guessing this issue is just caused by outdated dependencies.
`cargo install waycorner`

**Comment by siretty** [comment]
Thank you!

**Comment by AndreasBackx** [comment]
Thanks for fixing @siretty. New version pushed that will soon be available for those using AUR and cargo.
