### ISSUE TITLE
Seperate command per corner/edge

### ISSUE THREAD

**Issue by pancsta** [AndreasBackx/waycorner#23]
How to execute a different command for each corner / edge? The following **does not** work:

```
[left]
enter_command = [ "sway-hot-edge", "left" ]

[top]
enter_command = [ "sway-hot-edge", "top" ]

[right]
enter_command = [ "sway-hot-edge", "right" ]

[bottom]
enter_command = [ "sway-hot-edge", "bottom" ]

locations = ["left", "right", "top", "bottom"]
```

Only the last `enter_command` is executed.

thx

**Comment by AndreasBackx** [comment]
You need to specify `locations` for each item. Your items here are `left`, `top`, `right`, and `bottom`. README has a full example for each item and its config settings. If you're still confused, I recommend having a look at how [TOML](https://toml.io/en/) works.
