### ISSUE TITLE
Include all mouse controls for trigger

### ISSUE THREAD

**Issue by veganomy** [AndreasBackx/waycorner#28]
I've saw this project and I thought "why would someone want to accidentally trigger stuff with their mouse ?" [And I thought your principle was very unusual](https://github.com/AndreasBackx/waycorner/issues/13#issuecomment-2254639486).

The project name is `waycorner`, not `wayhover`. It's supposed to have all kinds of mouse triggers like left click, right click, middle click, scroll up, scroll down, etc. instead of just hover to trigger.  

Seems like an unusual stance for this wayland project. I respect your ideology. But it does not go well with this project name. It's better if the project is renamed to `wayhover` because if someone else writes a project where all mouse controls are utilized, they'd misguided by this project's name.

_Originally posted by @veganomy in https://github.com/AndreasBackx/waycorner/issues/13#issuecomment-2561320103_

**Comment by AndreasBackx** [comment]
If you want a particular feature. A good start would be to be respectful. Considering this nor the other comment are, I do not want to deal with someone like you. If anyone else is interested in this, feel free to create a new issue. There's always the possibility of convincing me with your arguments. Though there's no possibility to convince me with rudeness or entitlement.

This all especially when no work is being put in from the end of the requester. The code is open source and you may propose contributions and communicate openly. The overall point of `waycorner` is to be "Hot corners but for Wayland". There can be some leeway in that, but again let's be respectful. Right now, this is not planned unless there possibly is good reason to. It'll also likely not happen without someone coming forward and dedicating time for it. I don't see a use for it myself so I likely won't be the one implementing it.

**Comment by veganomy** [comment]
Too bad you couldn't handle good criticism. Arguments were already there on the table when it comes to the project. `waycorner` means something that can be triggered in a wayland session through 4 corners of the screen. That can be in 5 no of ways through 5 mouse actions. And you somehow decided to not have any of those actions and go with hover assuming this is what a lazy person is supposed to do. It's not a valid preassumption. You have to respond with valid counter arguments instead of bashing the messenger's attitude and thrashing the whole issue.  
If you'd be using your own project, that would actually be the first step why these discussions come in the first place.

I can't be more respectful than this. I'd stop here before anyone comes to this project and reads all these and understands the gist on why the discussion on this enhancement isn't going forward.

**Comment by AndreasBackx** [comment]
Alright, I'm not wasting my time arguing about this. For context to those reading this later, this was the comment on #13 that I replied to. These edits can only be seen by me and @veganomy.

> Excuse me. I don't use any bars because they suck. They literally stare to my soul every second. I'm a very minimalist dwm user with zero bars and window switchers.
> 
> I've saw waycorner project and I thought "why would someone want to accidentally trigger stuff with their mouse ?"
And I saw this issue and thought your principle was very stupid.
> 
> The project name is waycorner, not wayhover. It's supposed to have all kinds of mouse triggers like left click, right click, middle click, scroll up, scroll down, etc. instead of just hover to trigger. Seems like an unusual stance for this wayland project.
> 
> It's better if the project is renamed to wayhover because if someone else writes a project where all mouse controls are utilized, they'd misguided by this project's name.

Locking this issue and the other so we do not have to look at these messages. I've also blocked @veganomy as again, I'd rather spend my time communicating properly.

Again, anyone interested in this feature. Please comment on #13 with arguments in favour of the feature. Though there will need to be someone who steps up to implement the features. I open sourced waycorner because I needed these features. I unfortunately don't have the time to implement features that I don't plan on using.
