### ISSUE TITLE
[Feature Request] Support for enterring and exiting hot corners

### ISSUE THREAD

**Issue by jinnko** [AndreasBackx/waycorner#4]
It appears a command can only be triggered on entering the corner.  Would it be possible to also detect leaving the hot corner?

As an example of a use case, swaywm and waybar now support making the bar hidden unless the mod key is pressed.  Similarly I'd like to show the bar when touching the corner, and return to hiding the bar when leaving the corner.

**Comment by AndreasBackx** [comment]
Looks like a valid use case. Should be relatively simple to add as well. I'm up for reviewing any PRs, though cannot promise that I will have the time available myself. Up for answering any questions as well if you want to work on a PR.
