### ISSUE TITLE
[Feature request] Different timeouts for enter and exit commands

### ISSUE THREAD

**Issue by jhpaques** [AndreasBackx/waycorner#8]
Use case: I use hot corners to auto-hide my waybar, but I would like it to appear rapidly (enter command) but to disappear slowly (exit command) so that I have the time to click on a widget for example.

**Comment by jhpaques** [comment]
I solved this for my use case with #9: setting up two corners on top of each other (one with the enter command, the other with the exit command), with the former being drawn consistently on top of the latter.

**Comment by AndreasBackx** [comment]
Going to close this for now due to the lack of response. Feel free to open this again in the future, or anyone else who would like this feature.
